In [2]:
from numpy import *

In [5]:
arr = linspace(0,15,16)
print(arr)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15.]


In [6]:
arr =arange(1,15,2)
print(arr)

[ 1  3  5  7  9 11 13]


In [7]:
arr0 = zeros(5)
arr1 = ones(5)
arr1Int = ones(5, int)
print(arr0)
print(arr1)
print(arr1Int)

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[1 1 1 1 1]
