In [1]:
from numpy import *

In [2]:
arr = array([[1,2,3], [4,5,6], [7,8,9]])

In [3]:
# convert to 1D
arrFlat = arr.flatten();
print(arrFlat)

[1 2 3 4 5 6 7 8 9]


In [7]:
#Creating matrix
m = matrix(arr)
print(m)

m2 = matrix('1 2 3; 4 5 6; 7 8 9')
m3 = matrix('1 2 3; 4 5 6; 7 8 9')
print(m2)
print("---")
print(m2 * m3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
---
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]
